[package]
name = "reqwest-digest"
version = "0.1.0"
authors = ["David Webb <david@dpwlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
hex = "0.4"
rand = "0.7"
md-5 = "0.8"
sha2 = "0.8"
digest = "0.8"
regex = "1"
reqwest = "0.10"
url = "2.1"
