[package]
name = "reqwest-digest"
version = "0.1.0"
authors = ["David Webb <david@dpwlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
digest-access = { path = "../digest-access", features = ["from-headers"] }
http = "0.2"
reqwest = "0.10"
url = "2.1"

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
